language en_US.UTF-8
set nocompatible " Use vim default

"------------PATHOGEN-----------
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

"------------MISCELANEOUS------
syntax enable

set noswapfile " No need of .swap files with good backup systems

set nolazyredraw " No redrawing while executing macros

let mapleader = ","

nnoremap <silent> <C-l> :nohl<CR><C-l> " Remove hilighting

" resize vertical split window
nmap <C-Up> <C-w>>
nmap <C-Down> <C-w><

set backspace=indent,eol,start " Allow backspace over anything"

set complete=.,w,b,u,t,i " Autocompletes

"------------DISPLAY------------
" Colorscheme
set background=dark
let g:solarized_termtrans=1
let g:solarized_termcolors=256
let g:solarized_contrast="high"
let g:solarized_visibility="high"
colorscheme solarized

" Feature display
set number " Show line numbers
set ruler " (Bottom-right) Show line/col position
set ls=2 " (Bottom) path/filename + ruler
set cursorline " Highlight current line
set mouse=a   " Enable mouse selection
set wildmenu " (Bottom) Enable menu selection 

"------------Vim tabs-----------
ca tn tabnew
map <S-j> gT<CR>
map <S-k> gt<CR>

"------------SEARCH------------
set ignorecase  " Case insensitive search
set smartcase 
set incsearch   " Incremental search
set hlsearch
vnoremap <C-r> "hy:%s/<C-r>h//gc<left><left><left>  " Search and replace 

"------------INDENTATION-------
set autoindent
set smartindent
" filetype plugin on
filetype indent on

"------------TABS--------------
set tabstop=2
set shiftwidth=2
set expandtab

"------------COMMAND SHORTCUT----
" Substitue : for ;
" No more shift pressing!
nnoremap ; :
nnoremap : ;
vnoremap ; :
vnoremap : ;

"------------NAVIGATION---------
" Window navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

"------------COMMAND-T----------
noremap <C-t> <Esc>:CommandT<CR>
noremap <leader>m <Esc>:CommandTBuffer<CR>
noremap <leader>o <Esc>:CommandTFlush<CR>

"------------CTAGS--------------
set tags=tags
nnoremap <F8> :!/usr/bin/ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>

let Tlist_Ctags_Cmd = "/usr/bin/ctags"
let Tlist_WinWidth = 45
nnoremap <F4> :TlistToggle<cr>


autocmd FileType html,htmldjango,jinjahtml,eruby,mako let b:closetag_html_style=1
autocmd FileType html,xhtml,xml,htmldjango,jinjahtml,eruby,mako source ~/.vim/bundle/closetag/plugin/closetag.vim
